DELIMITER $$
CREATE PROCEDURE `zDP_MC40200SI`(
	IN `CURNCYID` char(15),
	IN `CURRNIDX` smallint(6),
	IN `NOTEINDX` decimal(19,5),
	IN `CRNCYDSC` char(31),
	IN `CRNCYSYM` char(3),
	IN `CNYSYMAR_1` smallint(6),
	IN `CNYSYMAR_2` smallint(6),
	IN `CNYSYMAR_3` smallint(6),
	IN `CYSYMPLC` smallint(6),
	IN `INCLSPAC` tinyint(4),
	IN `NEGSYMBL` smallint(6),
	IN `NGSMAMPC` smallint(6),
	IN `NEGSMPLC` smallint(6),
	IN `DECSYMBL` smallint(6),
	IN `DECPLCUR` smallint(6),
	IN `THOUSSYM` smallint(6),
	IN `CURTEXT_1` char(25),
	IN `CURTEXT_2` char(25),
	IN `CURTEXT_3` char(25),
	IN `ISOCURRC` char(3),
	IN `CURLNGID` smallint(6),
	OUT `DEX_ROW_ID` INT
)
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
COMMENT ''
BEGIN
	INSERT INTO MC40200 (CURNCYID, CURRNIDX, NOTEINDX, CRNCYDSC, CRNCYSYM, CNYSYMAR_1, CNYSYMAR_2, CNYSYMAR_3, CYSYMPLC, INCLSPAC, NEGSYMBL, NGSMAMPC, NEGSMPLC, DECSYMBL, DECPLCUR, THOUSSYM, CURTEXT_1, CURTEXT_2, CURTEXT_3, ISOCURRC, CURLNGID, DEX_ROW_TS) 
	VALUES              (CURNCYID, CURRNIDX, NOTEINDX, CRNCYDSC, CRNCYSYM, CNYSYMAR_1, CNYSYMAR_2, CNYSYMAR_3, CYSYMPLC, INCLSPAC, NEGSYMBL, NGSMAMPC, NEGSMPLC, DECSYMBL, DECPLCUR, THOUSSYM, CURTEXT_1, CURTEXT_2, CURTEXT_3, ISOCURRC, CURLNGID, NOW());
	SET DEX_ROW_ID = LAST_INSERT_ID();
	SELECT DEX_ROW_ID;
END
$$