CREATE DEFINER=`udyr0atmn7vmmvqf`@`%` PROCEDURE `DYNAMICS`.`zDP_MC60100SS_1`(IN `CMPANYID_1` SMALLINT, IN `CURNCYID_1` CHAR(15))
BEGIN
	SELECT CMPANYID, CURNCYID, INACTIVE, DEX_ROW_ID FROM MC60100 WHERE CMPANYID = CMPANYID_1 AND CURNCYID = CURNCYID_1  ORDER BY CMPANYID ASC, CURNCYID ASC LIMIT 1;

END;