
CREATE TABLE `MC40200` (
  `CURNCYID` char(15) NOT NULL,
  `CURRNIDX` smallint(6) NOT NULL,
  `NOTEINDX` decimal(19,5) NOT NULL,
  `CRNCYDSC` char(31) NOT NULL,
  `CRNCYSYM` char(3) NOT NULL,
  `CNYSYMAR_1` smallint(6) NOT NULL,
  `CNYSYMAR_2` smallint(6) NOT NULL,
  `CNYSYMAR_3` smallint(6) NOT NULL,
  `CYSYMPLC` smallint(6) NOT NULL,
  `INCLSPAC` tinyint(4) NOT NULL,
  `NEGSYMBL` smallint(6) NOT NULL,
  `NGSMAMPC` smallint(6) NOT NULL,
  `NEGSMPLC` smallint(6) NOT NULL,
  `DECSYMBL` smallint(6) NOT NULL,
  `DECPLCUR` smallint(6) NOT NULL,
  `THOUSSYM` smallint(6) NOT NULL,
  `CURTEXT_1` char(25) NOT NULL,
  `CURTEXT_2` char(25) NOT NULL,
  `CURTEXT_3` char(25) NOT NULL,
  `ISOCURRC` char(3) NOT NULL,
  `CURLNGID` smallint(6) NOT NULL,
  `DEX_ROW_TS` datetime NOT NULL,
  `DEX_ROW_ID` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`DEX_ROW_ID`)
)
