
CREATE TABLE IF NOT EXISTS `SY01400` (
  `USERID` varchar(255) NOT NULL,
  `USERNAME` varchar(255) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `DEX_ROW_ID` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`DEX_ROW_ID`)
) 