-- DYNAMICS.MC60100 definition

CREATE TABLE `MC60100` (
  `CMPANYID` smallint(6) NOT NULL,
  `CURNCYID` char(15) NOT NULL,
  `INACTIVE` tinyint(4) NOT NULL,
  `DEX_ROW_ID` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`CMPANYID`,`CURNCYID`),
  KEY `DEX_ROW_ID` (`DEX_ROW_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;